package com.spring.demo.springbootexample.pojo;

public class BaseAdminPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.descpt
     *
     * @mbggenerated
     */
    private String descpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_admin_permission.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.id
     *
     * @return the value of base_admin_permission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.id
     *
     * @param id the value for base_admin_permission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.name
     *
     * @return the value of base_admin_permission.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.name
     *
     * @param name the value for base_admin_permission.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.pid
     *
     * @return the value of base_admin_permission.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.pid
     *
     * @param pid the value for base_admin_permission.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.descpt
     *
     * @return the value of base_admin_permission.descpt
     *
     * @mbggenerated
     */
    public String getDescpt() {
        return descpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.descpt
     *
     * @param descpt the value for base_admin_permission.descpt
     *
     * @mbggenerated
     */
    public void setDescpt(String descpt) {
        this.descpt = descpt == null ? null : descpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.url
     *
     * @return the value of base_admin_permission.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.url
     *
     * @param url the value for base_admin_permission.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.create_time
     *
     * @return the value of base_admin_permission.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.create_time
     *
     * @param createTime the value for base_admin_permission.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.update_time
     *
     * @return the value of base_admin_permission.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.update_time
     *
     * @param updateTime the value for base_admin_permission.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_admin_permission.del_flag
     *
     * @return the value of base_admin_permission.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_admin_permission.del_flag
     *
     * @param delFlag the value for base_admin_permission.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}