package com.spring.demo.springbootexample.mapper;

import com.spring.demo.springbootexample.pojo.BaseAdminPermission;
import com.spring.demo.springbootexample.pojo.BaseAdminPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseAdminPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int countByExample(BaseAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int deleteByExample(BaseAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int insert(BaseAdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int insertSelective(BaseAdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    List<BaseAdminPermission> selectByExample(BaseAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    BaseAdminPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseAdminPermission record, @Param("example") BaseAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseAdminPermission record, @Param("example") BaseAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseAdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_admin_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseAdminPermission record);
}