spring:
  profiles:
    active: dev
  #默认使用开发坏境

#配置PageHelper插件
pagehelper:
  #数据库方言
  auto-dialect: mysql
  #启用合理化，如果pageNum < 1会查询第一页，如果pageNum >pages会查询最后一页
  reasonable: true
mybatis:
  #mapper.xml包地址
  mapper-locations: classpath:mapper/*.xml
  #pojo包生成地址
  type-aliases-package: com.spring.demo.springbootexample.pojo



